# gen_aes_sbox.py
# 按 FIPS-197 的 GF(2^8) 逆元 + affine transform
# 自动生成 rtl/aes_sbox.v。

from pathlib import Path


def gf_mul(a, b):
    """AES 有限域 GF(2^8) 乘法，模多项式为 0x11B。"""
    result = 0

    for _ in range(8):
        if b & 1:
            result ^= a

        high_bit = a & 0x80
        a = (a << 1) & 0xFF

        if high_bit:
            a ^= 0x1B

        b >>= 1

    return result


def gf_pow(a, exponent):
    """有限域快速幂。非零 a 的逆元是 a^254。"""
    result = 1

    while exponent:
        if exponent & 1:
            result = gf_mul(result, a)

        a = gf_mul(a, a)
        exponent >>= 1

    return result


def aes_sbox(x):
    """
    AES 前向 S-box：
    1) x=0 时逆元定义为 0；否则计算 GF(2^8) 乘法逆元 x^254。
    2) 对逆元执行 AES 固定 affine transform。
    """
    inverse = 0 if x == 0 else gf_pow(x, 254)

    # y = inverse XOR rol8(inverse,1) XOR rol8(...,2/3/4) XOR 0x63
    y = inverse

    for shift in (1, 2, 3, 4):
        y ^= ((inverse << shift) | (inverse >> (8 - shift))) & 0xFF

    return y ^ 0x63


def main():
    output_path = Path(__file__).resolve().parents[1] / "aes_sbox.v"

    with output_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("// AUTO-GENERATED by tools/gen_aes_sbox.py; do not hand-edit.\n")
        f.write("// AES forward S-box, FIPS-197.\n\n")
        f.write("module aes_sbox (\n")
        f.write("    input  wire [7:0] sbox_in,\n")
        f.write("    output reg  [7:0] sbox_out\n")
        f.write(");\n\n")
        f.write("    always @(*) begin\n")
        f.write("        case (sbox_in)\n")

        for x in range(256):
            f.write(f"            8'h{x:02X}: sbox_out = 8'h{aes_sbox(x):02X};\n")

        f.write("            default: sbox_out = 8'h00;\n")
        f.write("        endcase\n")
        f.write("    end\n\n")
        f.write("endmodule\n")

    # 三个 FIPS-197 可快速确认的点。
    assert aes_sbox(0x00) == 0x63
    assert aes_sbox(0x53) == 0xED
    assert aes_sbox(0xFF) == 0x16

    print(f"PASS: generated {output_path}")


if __name__ == "__main__":
    main()